quora1/config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'
  get 'ask/index'
  get 'welcome/index'
  devise_for :users
  resources :questions
  # root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
end

quora1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quora1/app/models/question.rb
class Question < ApplicationRecord
end

quora1/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

quora1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

quora1/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    # render plain: params[:question].inspect
    @question = Question.new(question_params)
 
    @question.save
    redirect_to @question
  end

  private
  def question_params
    params.require(:question).permit(:question)
  end
end

quora1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

quora1/app/helpers/application_helper.rb
module ApplicationHelper
end

quora1/app/helpers/ask_helper.rb
module AskHelper
end

quora1/app/helpers/questions_helper.rb
module QuestionsHelper
end

quora1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

quora1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%= link_to "AskQuestion", questions_path, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>


  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

quora1/app/views/questions/index.html.erb
<%= form_with scope: :question, url: questions_path, local: true do |form| %>
  <p>
    <%= form.label :enter_your_question %><br>
    <%= form.text_area :question %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

quora1/app/views/questions/show.html.erb
<p>
  <strong>Enter Your Question:</strong>
  <%= @question.question %>
</p>
 

quora1/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>